
"""Initial migration

Revision ID: 74b5000dff55
Revises: 'None'
Create Date: 2025-08-21 16:43:49.879748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74b5000dff55'
down_revision = 'None'
branch_labels = 'None'
depends_on = 'None'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usertype',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usertype_id'), 'usertype', ['id'], unique=False)
    op.create_index(op.f('ix_usertype_name'), 'usertype', ['name'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_type_id', sa.Uuid(), nullable=False),
    sa.Column('extra_fields', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_type_id'], ['usertype.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_usertype_name'), table_name='usertype')
    op.drop_index(op.f('ix_usertype_id'), table_name='usertype')
    op.drop_table('usertype')
    # ### end Alembic commands ###
