"""order v2: vouchers, shipping_config, order fields

Revision ID: 8fa10758d66c
Revises: c1c22a06f60f
Create Date: 2025-08-27 19:47:08.979248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fa10758d66c'
down_revision: Union[str, Sequence[str], None] = 'c1c22a06f60f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shippingconfig',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base_fee_first_item', sa.Float(), nullable=False),
    sa.Column('additional_fee_per_item', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('rules', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('voucher',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('discount_type', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('scope', sa.String(), nullable=False),
    sa.Column('target_user_type_id', sa.Uuid(), nullable=True),
    sa.Column('target_user_id', sa.Uuid(), nullable=True),
    sa.Column('min_quantity', sa.Integer(), nullable=False),
    sa.Column('per_unit', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('valid_from', sa.DateTime(), nullable=True),
    sa.Column('valid_to', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['target_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['target_user_type_id'], ['usertype.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voucher_code'), 'voucher', ['code'], unique=True)
    op.create_index(op.f('ix_voucher_id'), 'voucher', ['id'], unique=False)
    op.create_table('voucherproductlink',
    sa.Column('voucher_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['voucher_id'], ['voucher.id'], ),
    sa.PrimaryKeyConstraint('voucher_id', 'product_id')
    )
    op.add_column('order', sa.Column('subtotal_amount', sa.Float(), nullable=False, server_default='0'))
    op.add_column('order', sa.Column('discount_amount', sa.Float(), nullable=False, server_default='0'))
    op.add_column('order', sa.Column('shipping_amount', sa.Float(), nullable=False, server_default='0'))
    op.add_column('order', sa.Column('currency', sa.String(), nullable=False, server_default='MYR'))
    op.add_column('order', sa.Column('payment_method', sa.String(), nullable=True))
    op.add_column('order', sa.Column('payment_intent_id', sa.String(), nullable=True))
    op.add_column('order', sa.Column('shipping_address', sa.JSON(), nullable=True))
    op.add_column('order', sa.Column('billing_address', sa.JSON(), nullable=True))
    op.add_column('order', sa.Column('remark', sa.String(), nullable=True))
    op.add_column('orderitem', sa.Column('snapshot_name', sa.String(), nullable=True))
    op.add_column('orderitem', sa.Column('snapshot_price', sa.Float(), nullable=True))
    op.add_column('orderitem', sa.Column('snapshot_media_url', sa.String(), nullable=True))
    op.add_column('orderitem', sa.Column('line_subtotal', sa.Float(), nullable=False, server_default='0'))
    op.add_column('orderitem', sa.Column('discount_amount', sa.Float(), nullable=False, server_default='0'))
    op.add_column('orderitem', sa.Column('line_total', sa.Float(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orderitem', 'line_total')
    op.drop_column('orderitem', 'discount_amount')
    op.drop_column('orderitem', 'line_subtotal')
    op.drop_column('orderitem', 'snapshot_media_url')
    op.drop_column('orderitem', 'snapshot_price')
    op.drop_column('orderitem', 'snapshot_name')
    op.drop_column('order', 'remark')
    op.drop_column('order', 'billing_address')
    op.drop_column('order', 'shipping_address')
    op.drop_column('order', 'payment_intent_id')
    op.drop_column('order', 'payment_method')
    op.drop_column('order', 'currency')
    op.drop_column('order', 'shipping_amount')
    op.drop_column('order', 'discount_amount')
    op.drop_column('order', 'subtotal_amount')
    op.drop_table('voucherproductlink')
    op.drop_index(op.f('ix_voucher_id'), table_name='voucher')
    op.drop_index(op.f('ix_voucher_code'), table_name='voucher')
    op.drop_table('voucher')
    op.drop_table('shippingconfig')
    # ### end Alembic commands ###
