"""Add applied_voucher_code to Order model

Revision ID: ae0af1afc004
Revises: a58c90e29012
Create Date: 2025-08-29 22:20:13.966073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ae0af1afc004'
down_revision: Union[str, Sequence[str], None] = 'a58c90e29012'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('applied_voucher_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'applied_voucher_code')
    # ### end Alembic commands ###
