"""add timestamps to remaining models

Revision ID: ea21ff11a8e2
Revises: 97766d342408
Create Date: 2025-08-24 19:48:03.996632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ea21ff11a8e2'
down_revision: Union[str, Sequence[str], None] = '97766d342408'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cartitem', sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False))
    op.add_column('cartitem', sa.Column('updated_at', sa.DateTime(), server_default=sa.func.now(), nullable=False))
    op.drop_column('cartitem', 'added_at')
    op.add_column('orderitem', sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False))
    op.add_column('orderitem', sa.Column('updated_at', sa.DateTime(), server_default=sa.func.now(), nullable=False))
    op.add_column('usertype', sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False))
    op.add_column('usertype', sa.Column('updated_at', sa.DateTime(), server_default=sa.func.now(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usertype', 'updated_at')
    op.drop_column('usertype', 'created_at')
    op.drop_column('orderitem', 'updated_at')
    op.drop_column('orderitem', 'created_at')
    op.add_column('cartitem', sa.Column('added_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('cartitem', 'updated_at')
    op.drop_column('cartitem', 'created_at')
    # ### end Alembic commands ###
