services:
  backend:
    volumes:
      - ./app:/app/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ../newmedica-frontend
      dockerfile: Dockerfile
      target: development  # Use a development stage in the Dockerfile
    volumes:
      - ../newmedica-frontend:/app
      - /app/node_modules
    command: npm run dev
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:8000
      - INTERNAL_API_BASE_URL=http://backend:8000
