name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend image
        uses: docker/build-push-action@v4
        with:
          context: ./newmedica-backend
          file: ./newmedica-backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/newmedica-backend:latest

      - name: Build and push frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./newmedica-frontend
          file: ./newmedica-frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/newmedica-frontend:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          key: ${{ secrets.PROD_SSH_KEY }}
          script: |
            cd /path/to/your/project
            docker-compose -f docker-compose.yml -f docker-compose.production.yml pull
            docker-compose -f docker-compose.yml -f docker-compose.production.yml up -d
